
version: 1.0.{build}
branches:
  only:
  - main
skip_commits:
  files:
    - README.md
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: nuget restore yescrypt.sln
build:
  project: yescrypt.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: jKuArhblUbUXHVHfnm7NAyhU7efQTNCWbP7XQEcyS2FnPQVWLMyBMhOwqMfRXf/z
notifications:
- provider: Email
  to:
  - matt@fasterlimit.com
  - petrsnd@gmail.com
  subject: yescrypt-net build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
